# Generated by Django 4.2.3 on 2023-07-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='view',
            field=models.BooleanField(default=True),
        ),
    ]
